### ISSUE TITLE
The code on the home page has spelling errors, right?

### ISSUE THREAD

**Issue by smartPiz** [Mijick/CalendarView#31]
@State private var selectedDate: Data? = nil 
maybe 
@State private var selectedDate: Date? = nil

**Comment by FulcrumOne** [comment]
Hey @smartPiz,

Yeah, it's a typo 😄
Thanks for noticing, I'll fix it!

**Comment by smartPiz** [comment]
> Hey @smartPiz,
> 
> Yeah, it's a typo 😄 Thanks for noticing, I'll fix it!

Thumbs up for your excellent work.

**Comment by FulcrumOne** [comment]
Thanks @smartPiz! And sorry for not maintaining this library for so long, but we have four others in the current queue (after that we're going to introduce some features here).
